fabric-ca-server:
  image: hyperledger/fabric-ca
  container_name: fabric-ca-server
  ports:
    - "7054:7054"
  environment:
    - FABRIC_CA_HOME=/var/hyperledger/fabric-ca
  volumes:
    - /var/hyperledger/fabric-ca:/var/hyperledger/fabric-ca
  command: sh -c 'fabric-ca-server start -b admin:adminpw'
